import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Resify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <link
          rel="stylesheet"
          href="https://use.typekit.net/bgq4hkc.css"
        ></link>

        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
